--DROP TABLES
drop table product;
drop table product_type;
drop table manufacturer;
drop sequence product_seq;
drop sequence product_type_seq;
drop sequence manufacturer_seq;
create sequence product_seq;
create sequence product_type_seq;
create sequence manufacturer_seq;

--------------------------------------------------------
--  DDL for Table MANUFACTURER
--------------------------------------------------------

  CREATE TABLE "AGRII"."MANUFACTURER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
  "DELIVERY" VARCHAR2(200) default 'Unknown',
  "SURCHARGE_1" VARCHAR2(200) default 'Unknown',
  "SURCHARGE_2" VARCHAR2(200) default 'Unknown',
  "SURCHARGE_3" VARCHAR2(200) default 'Unknown',
  "SURCHARGE_4" VARCHAR2(200) default 'Unknown',
  "MINIMUM_LOAD" VARCHAR2(200) default 'Unknown',
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT user, 
	"ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "AGRII"."PRODUCT" 
   (	"ID" NUMBER, 
	"MANUFACTURER_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"N" NUMBER, 
	"P" NUMBER, 
	"K" NUMBER, 
	"SO3" NUMBER, 
	"MGO" NUMBER, 
	"CA" NUMBER, 
	"PRODUCT_TYPE_ID" NUMBER, 
	"KG500" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"KG1000" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PRICE" NUMBER, 
	"PRICE_1" NUMBER, 
	"PRICE_2" NUMBER, 
	"PRICE_3" NUMBER, 
	"COMMENT" VARCHAR2(200), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT user, 
	"ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_TYPE
--------------------------------------------------------

  CREATE TABLE "AGRII"."PRODUCT_TYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"CREATED_BY" VARCHAR2(50 BYTE) DEFAULT user, 
	"ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010398
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGRII"."SYS_C0010398" ON "AGRII"."MANUFACTURER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010399
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGRII"."SYS_C0010399" ON "AGRII"."PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010397
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGRII"."SYS_C0010397" ON "AGRII"."PRODUCT_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MANUFACTURER
--------------------------------------------------------

  ALTER TABLE "AGRII"."MANUFACTURER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "AGRII"."PRODUCT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_TYPE
--------------------------------------------------------

  ALTER TABLE "AGRII"."PRODUCT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "AGRII"."PRODUCT" ADD CONSTRAINT "PRODUCT_MANUFACTURER_KF" FOREIGN KEY ("MANUFACTURER_ID")
	  REFERENCES "AGRII"."MANUFACTURER" ("ID") ENABLE;
  ALTER TABLE "AGRII"."PRODUCT" ADD CONSTRAINT "PRODUCT_TYPE_FK" FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "AGRII"."PRODUCT_TYPE" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger MANUFACTURER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGRII"."MANUFACTURER_TRG" before
  INSERT ON MANUFACTURER FOR EACH row  WHEN (new.id IS NULL) BEGIN
  SELECT MANUFACTURER_seq.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "AGRII"."MANUFACTURER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGRII"."PRODUCT_TRG" before
  INSERT ON product FOR EACH row  WHEN (new.id IS NULL) BEGIN
  SELECT product_seq.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "AGRII"."PRODUCT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGRII"."PRODUCT_TYPE_TRG" before
  INSERT ON product_type FOR EACH row  WHEN (new.id IS NULL) BEGIN
  SELECT product_type_seq.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "AGRII"."PRODUCT_TYPE_TRG" ENABLE;
